name: fr_nav
description: Flutter Rapid Navigation (fr_nav)
version: 1.0.0
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  convex_bottom_bar: ^3.2.0
  fr_core:
    path: ../fr_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
